# Generated by Django 5.2.5 on 2025-09-08 16:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom', models.CharField(max_length=255)),
                ('solde', models.DecimalField(decimal_places=0, max_digits=12)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompteDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom', models.CharField(max_length=255)),
                ('solde', models.DecimalField(decimal_places=0, max_digits=12)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompteHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=255)),
                ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Observation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                ('montant_journalier', models.DecimalField(decimal_places=0, max_digits=12)),
                ('nombre_jours_total', models.PositiveIntegerField(default=31)),
                ('jours_verse', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('encours', models.BooleanField(default=True)),
                ('retrait_effectue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketRetire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                ('montant_journalier', models.DecimalField(decimal_places=0, max_digits=12)),
                ('nombre_jours_total', models.PositiveIntegerField(default=31)),
                ('jours_verse', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_retrait', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_retiré', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ValeurAjoutee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=255)),
                ('valeur', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom', models.CharField(db_index=True, max_length=40)),
                ('prenom', models.CharField(db_index=True, max_length=40)),
                ('telephone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('genre', models.CharField(max_length=15)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naiss', models.CharField(db_index=True, max_length=30)),
                ('fonction', models.CharField(choices=[('SUPER', 'Super Utilisateur'), ('USER', 'Utilisateur')], max_length=256, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TicketCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='finance.ticket')),
            ],
        ),
    ]
