# Generated by Django 5.2.5 on 2025-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketretire',
            name='total_credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='fonction',
            field=models.CharField(choices=[('SUPER', 'ADMIN'), ('USER', 'USER')], max_length=256, null=True),
        ),
    ]
